"""Runtime QSS renderer for the PySide6 themes.

Turns a theme's color **tokens** — whether a built-in theme from
``gui_qt.themes`` or a user-made custom theme — into the QSS string
Qt's ``setStyleSheet`` consumes.

This lives inside the package (not ``tools/``) on purpose: the running
app and the Theme Maker's live preview render *any* token set on the
fly, so themes are no longer limited to the committed ``.qss`` files.
``tools/build_qss.py`` still imports ``render_qss`` from here to
(re)generate the built-in ``.qss`` artifacts at dev time.
"""

from __future__ import annotations

from typing import Mapping

from gui_qt.themes import TOKEN_KEYS, Theme


# ---------------------------------------------------------------------------
# QSS template
# ---------------------------------------------------------------------------
#
# We template the QSS with named ``{tokens[key]}`` placeholders that
# get filled per theme.  Keep this template **simple and Qt-idiomatic**;
# we're not trying to recreate the polish from ``docs/design/themes/
# styles.css`` (sheen overlays, color-mix, keyframe animations).  Those
# are CSS-only and don't translate cleanly to QSS.  The goal here is:
#
#   1) Every theme loads without parse errors.
#   2) Default Qt widgets get a coherent base palette.
#   3) The wizard objectNames already in ``gui_qt/setup_wizard.py``
#      are styled to their semantic role:
#         #confirmButton   → ``go``      (primary CTA, "next/start")
#         #primaryButton   → ``info``    (workflow choice, e.g. movie/tv)
#         #secondaryButton → ``alt``     (workflow alt, e.g. standard)
#         #cancelButton    → muted/border (de-emphasised)
#   4) The classification labels ``#classificationLabel_MAIN`` /
#      ``EXTRA`` / ``DUPLICATE`` / ``UNKNOWN`` get distinct accent
#      colors — MAIN reads as success-toned, EXTRA as info-toned,
#      DUPLICATE/UNKNOWN as muted.
#
# Hover and disabled states are sketched but kept conservative — Phase
# 3c will iterate on them when the full main window comes online and
# we get more interaction surface to tune against.

_QSS_TEMPLATE = """\
/* ===========================================================================
 * {name} ({id}) — {family} family
 * Generated by tools/build_qss.py from gui_qt.themes.THEMES.
 * DO NOT EDIT BY HAND.  Edit the tokens in gui_qt/themes.py and re-run.
 *
 * {notes}
 * ===========================================================================
 */

/* ---- Base palette --------------------------------------------------- */

QMainWindow,
QDialog#wizardDialog,
QDialog {{
    background-color: {tokens[bg]};
    color: {tokens[fg]};
}}

QWidget {{
    background-color: transparent;
    color: {tokens[fg]};
    font-family: "Segoe UI", "Inter", system-ui, sans-serif;
    font-size: 13px;
}}

QFrame#sectionDivider {{
    background-color: {tokens[border]};
    max-height: 1px;
    border: none;
}}

/* ---- Settings dialog tab bar --------------------------------------- */
/* Qt's default styled-tab rendering leaves unselected tabs without
 * contrast on light surfaces (they vanish white-on-white).  Theme the
 * tabs explicitly: muted unselected labels, full-strength selected
 * label with an accent underline.  Reads correctly in light and dark. */

QTabWidget#settingsTabs::pane {{
    border: none;
}}

QTabBar::tab {{
    background: transparent;
    color: {tokens[muted]};
    padding: 8px 16px;
    border: none;
    border-bottom: 2px solid transparent;
}}

QTabBar::tab:hover {{
    color: {tokens[fg]};
}}

QTabBar::tab:selected {{
    color: {tokens[fg]};
    border-bottom: 2px solid {tokens[accent]};
}}

/* ---- Headers + section labels --------------------------------------- */

QLabel#stepHeader {{
    color: {tokens[accent]};
    font-size: 18px;
    font-weight: 700;
    padding: 8px 0 4px 0;
}}

QLabel#stepSubtitle {{
    color: {tokens[muted]};
    font-size: 12px;
    padding: 0 0 8px 0;
}}

QLabel#sectionHeader {{
    color: {tokens[muted]};
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 1px;
    padding: 12px 0 4px 0;
}}

QLabel#scaffoldingPlaceholder {{
    color: {tokens[muted]};
    font-size: 14px;
    padding: 24px;
}}

/* ---- Wizard rows + scrollers ---------------------------------------- */

QScrollArea#classifiedTitlesScroll {{
    background-color: {tokens[card]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
}}

QWidget#classifiedTitlesBody {{
    background-color: {tokens[card]};
}}

QFrame#classifiedTitleRow,
QFrame#contentMappingRow {{
    background-color: {tokens[card]};
    border-bottom: 1px solid {tokens[border]};
    padding: 6px 10px;
}}

QLabel#titleNumber {{
    color: {tokens[fg]};
    font-weight: 600;
}}

QLabel#confidencePercent,
QLabel#durationSize,
QLabel#titleReason,
QLabel#sessionDetailLine,
QLabel#scanSummaryRow,
QLabel#driveDiscType,
QLabel#destinationPath {{
    color: {tokens[muted]};
    font-size: 12px;
}}

/* Classification labels — MAIN reads success-toned, EXTRA info-toned,
 * DUPLICATE/UNKNOWN muted.  Per-category tinting helps users see at a
 * glance which titles will be ripped vs. ignored. */
QLabel#classificationLabel_MAIN {{
    color: {tokens[go]};
    font-weight: 600;
}}
QLabel#classificationLabel_EXTRA {{
    color: {tokens[info]};
    font-weight: 600;
}}
QLabel#classificationLabel_DUPLICATE,
QLabel#classificationLabel_UNKNOWN {{
    color: {tokens[muted]};
    font-weight: 600;
}}

/* ---- Tree view (output plan) ---------------------------------------- */

QTreeView#outputTreeView,
QTreeWidget#outputTreeView {{
    background-color: {tokens[input]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    selection-background-color: {tokens[selection]};
    selection-color: {tokens[selectionFg]};
}}

QTreeView::item:hover,
QTreeWidget::item:hover {{
    background-color: {tokens[hover]};
}}

QTreeView::item:selected,
QTreeWidget::item:selected {{
    background-color: {tokens[selection]};
    color: {tokens[selectionFg]};
}}

/* ---- Form controls -------------------------------------------------- */

QLineEdit,
QPlainTextEdit,
QTextEdit {{
    background-color: {tokens[input]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    padding: 6px 10px;
    selection-background-color: {tokens[selection]};
    selection-color: {tokens[selectionFg]};
}}

QLineEdit:hover,
QPlainTextEdit:hover,
QTextEdit:hover {{
    border-color: {tokens[muted]};
}}

QLineEdit:focus,
QPlainTextEdit:focus,
QTextEdit:focus {{
    border-color: {tokens[accent]};
}}

QComboBox {{
    background-color: {tokens[input]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    padding: 5px 10px;
    min-height: 20px;
}}

QComboBox:hover {{
    border-color: {tokens[accent]};
}}

QComboBox:focus {{
    border-color: {tokens[accent]};
}}

QComboBox::drop-down {{
    subcontrol-origin: padding;
    subcontrol-position: top right;
    width: 18px;
    border: none;
}}

QComboBox QAbstractItemView {{
    background-color: {tokens[card]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    selection-background-color: {tokens[selection]};
    selection-color: {tokens[selectionFg]};
    outline: none;
}}

/* Disabled combo entries use the theme's muted color so they read as
 * unavailable and stay legible in every theme - no baked hex. */
QComboBox QAbstractItemView::item:disabled {{
    color: {tokens[muted]};
}}

QCheckBox {{
    color: {tokens[fg]};
    spacing: 8px;
}}

QCheckBox::indicator {{
    width: 14px;
    height: 14px;
    border: 1px solid {tokens[border]};
    border-radius: 3px;
    background-color: {tokens[input]};
}}

QCheckBox::indicator:hover {{
    border-color: {tokens[accent]};
}}

QCheckBox::indicator:checked {{
    background-color: {tokens[go]};
    border-color: {tokens[go]};
}}

QCheckBox#contentMappingCheckbox {{
    /* same style as base QCheckBox; selector pinned for theming drift */
}}

/* ---- Buttons -------------------------------------------------------- */

QPushButton {{
    background-color: {tokens[card]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    padding: 7px 14px;
    font-weight: 500;
}}

QPushButton:hover {{
    background-color: {tokens[hover]};
    border-color: {tokens[accent]};
}}

QPushButton:pressed {{
    background-color: {tokens[hoverPressed]};
    border-color: {tokens[accent]};
}}

QPushButton:disabled {{
    color: {tokens[muted]};
    border-color: {tokens[border]};
    background-color: {tokens[card]};
}}

QPushButton:focus {{
    outline: none;
    border-color: {tokens[accent]};
}}

/* Primary CTA — "Next", "Confirm", "Start Rip".
 * Maps to the ``go`` role.  Bold + colored to draw the eye. */
QPushButton#confirmButton {{
    background-color: {tokens[go]};
    color: {tokens[goFg]};
    border: 1px solid {tokens[go]};
    font-weight: 700;
}}
QPushButton#confirmButton:hover {{
    background-color: {tokens[go]};
    border-color: {tokens[goFg]};
}}
QPushButton#confirmButton:pressed {{
    background-color: {tokens[goPressed]};
    border-color: {tokens[goFg]};
}}
QPushButton#confirmButton:disabled {{
    background-color: {tokens[card]};
    color: {tokens[muted]};
    border-color: {tokens[border]};
}}

/* Workflow choice button — "Movie", "TV".
 * Maps to the ``info`` role. */
QPushButton#primaryButton {{
    background-color: {tokens[info]};
    color: {tokens[infoFg]};
    border: 1px solid {tokens[info]};
    font-weight: 600;
}}
QPushButton#primaryButton:hover {{
    background-color: {tokens[info]};
    border-color: {tokens[infoFg]};
}}
QPushButton#primaryButton:pressed {{
    background-color: {tokens[infoPressed]};
    border-color: {tokens[infoFg]};
}}

/* Workflow alt button — "Standard".
 * Maps to the ``alt`` role. */
QPushButton#secondaryButton {{
    background-color: {tokens[alt]};
    color: {tokens[altFg]};
    border: 1px solid {tokens[alt]};
    font-weight: 600;
}}
QPushButton#secondaryButton:hover {{
    background-color: {tokens[alt]};
    border-color: {tokens[altFg]};
}}
QPushButton#secondaryButton:pressed {{
    background-color: {tokens[altPressed]};
    border-color: {tokens[altFg]};
}}

/* De-emphasised — "Cancel".  Just a bordered chip in the muted color. */
QPushButton#cancelButton {{
    background-color: transparent;
    color: {tokens[muted]};
    border: 1px solid {tokens[border]};
    font-weight: 500;
}}
QPushButton#cancelButton:hover {{
    color: {tokens[fg]};
    background-color: {tokens[hover]};
    border-color: {tokens[border]};
}}
QPushButton#cancelButton:pressed {{
    color: {tokens[fg]};
    background-color: {tokens[hoverPressed]};
    border-color: {tokens[accent]};
}}

/* ---- Progress / scrollbars ----------------------------------------- */

QProgressBar {{
    background-color: {tokens[input]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    text-align: center;
    color: {tokens[fg]};
    height: 8px;
}}

QProgressBar::chunk {{
    background-color: {tokens[accent]};
    border-radius: 6px;
}}

QScrollBar:vertical {{
    background: {tokens[bg]};
    width: 10px;
    margin: 0;
}}
QScrollBar::handle:vertical {{
    background: {tokens[border]};
    border-radius: 5px;
    min-height: 24px;
}}
QScrollBar::handle:vertical:hover {{
    background: {tokens[muted]};
}}
QScrollBar::add-line:vertical,
QScrollBar::sub-line:vertical {{
    height: 0;
    background: none;
}}

QScrollBar:horizontal {{
    background: {tokens[bg]};
    height: 10px;
    margin: 0;
}}
QScrollBar::handle:horizontal {{
    background: {tokens[border]};
    border-radius: 5px;
    min-width: 24px;
}}
QScrollBar::handle:horizontal:hover {{
    background: {tokens[muted]};
}}
QScrollBar::add-line:horizontal,
QScrollBar::sub-line:horizontal {{
    width: 0;
    background: none;
}}

/* ---- Themed window surfaces (Phase 3c-i) --------------------------- */
/* Layout chrome introduced by ``gui_qt/main_window.py`` and the
 * settings dialog.  Each rule targets the objectName the shell sets so
 * per-theme coloring happens entirely in QSS.  No colors hard-coded in
 * Python.  ``settingsDialogBody`` is the dialog's content container: a
 * top-level ``QDialog`` background isn't reliably painted over the
 * native window surface, so the dialog wraps its content in this named
 * child the same way the main window uses ``mainCentral``. */

QMainWindow#mainWindow,
QWidget#mainCentral,
QWidget#settingsDialogBody {{
    background-color: {tokens[bg]};
}}

/* App header — centered, accent-colored title with monospace subtitle */
QFrame#appHeader {{
    background-color: {tokens[card]};
    border-bottom: 1px solid {tokens[border]};
}}
QLabel#appHeaderTitle {{
    color: {tokens[accent]};
    font-size: 28px;
    font-weight: 700;
    letter-spacing: -0.5px;
}}
QLabel#appHeaderSubtitle {{
    color: {tokens[muted]};
    font-size: 11px;
    font-weight: 500;
    letter-spacing: 1.2px;
}}

/* Drive row */
QFrame#driveRow {{
    background-color: transparent;
}}
QLabel#driveLabel {{
    color: {tokens[muted]};
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 0.5px;
    margin-right: 4px;
}}
QComboBox#driveCombo {{
    background-color: {tokens[input]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    padding: 7px 12px;
    min-height: 22px;
}}
QComboBox#driveCombo:hover {{
    border-color: {tokens[accent]};
}}
QComboBox#driveCombo:focus {{
    border-color: {tokens[accent]};
}}
QPushButton#driveRefresh {{
    background-color: {tokens[input]};
    color: {tokens[muted]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    font-size: 16px;
    font-weight: 700;
}}
QPushButton#driveRefresh:hover {{
    background-color: {tokens[hover]};
    color: {tokens[accent]};
    border-color: {tokens[accent]};
}}
QPushButton#driveRefresh:pressed {{
    background-color: {tokens[hoverPressed]};
    color: {tokens[accent]};
    border-color: {tokens[accent]};
}}

/* Utility toolbar — top-docked QToolBar (replaces the chip row) */
QToolBar#utilityToolBar {{
    background-color: {tokens[bg]};
    border: none;
    border-bottom: 1px solid {tokens[border]};
    padding: 4px 16px;
    spacing: 4px;
}}
QToolBar#utilityToolBar::separator {{
    background-color: {tokens[border]};
    width: 1px;
    margin: 4px 8px;
}}
QToolButton#utilSettings,
QToolButton#utilUpdates,
QToolButton#utilCopyLog,
QToolButton#utilBrowse {{
    background-color: transparent;
    color: {tokens[muted]};
    border: 1px solid transparent;
    border-radius: 6px;
    padding: 6px 12px;
    font-size: 12px;
    font-weight: 500;
}}
QToolButton#utilSettings:hover,
QToolButton#utilUpdates:hover,
QToolButton#utilCopyLog:hover,
QToolButton#utilBrowse:hover {{
    background-color: {tokens[hover]};
    color: {tokens[fg]};
    border-color: {tokens[border]};
}}
QToolButton#utilSettings:pressed,
QToolButton#utilUpdates:pressed,
QToolButton#utilCopyLog:pressed,
QToolButton#utilBrowse:pressed {{
    background-color: {tokens[selection]};
    color: {tokens[fg]};
}}
QToolButton#utilSettings:focus,
QToolButton#utilUpdates:focus,
QToolButton#utilCopyLog:focus,
QToolButton#utilBrowse:focus {{
    border-color: {tokens[accent]};
    color: {tokens[fg]};
}}
/* Legacy QPushButton#utilXxx selectors kept while build_qss.py
 * regenerates the .qss files — purges below if anything else
 * still constructs the old chip row.  Safe to remove next pass. */
QPushButton#utilSettings,
QPushButton#utilUpdates,
QPushButton#utilCopyLog,
QPushButton#utilBrowse {{
    background-color: transparent;
    color: {tokens[muted]};
    border: 1px solid transparent;
    border-radius: 6px;
    padding: 6px 12px;
    font-size: 12px;
    font-weight: 500;
}}
QPushButton#utilSettings:hover,
QPushButton#utilUpdates:hover,
QPushButton#utilCopyLog:hover,
QPushButton#utilBrowse:hover {{
    background-color: {tokens[hover]};
    color: {tokens[fg]};
    border-color: {tokens[border]};
}}

/* Workflow button rows */
QFrame#primaryButtonRow,
QFrame#secondaryButtonRow {{
    background-color: transparent;
}}

/* Mode buttons — colored per role.  ObjectName prefix encodes role:
 *   modeGo*    → go    (TV, Movie — primary action)
 *   modeInfo*  → info  (Dump All Titles — secondary action)
 *   modeAlt*   → alt   (Organize MKVs — tertiary action)
 *   modeWarn*  → warn  (Prep MKVs — caution)
 */
QPushButton[objectName^="modeGo"] {{
    background-color: {tokens[go]};
    color: {tokens[goFg]};
    border: 1px solid {tokens[go]};
    border-radius: 6px;
    font-size: 13px;
    font-weight: 700;
}}
QPushButton[objectName^="modeGo"]:hover {{
    border-color: {tokens[goFg]};
}}
QPushButton[objectName^="modeGo"]:focus {{
    border-color: {tokens[goFg]};
}}
QPushButton[objectName^="modeGo"]:pressed {{
    background-color: {tokens[goPressed]};
    border-color: {tokens[goFg]};
}}
QPushButton[objectName^="modeInfo"] {{
    background-color: {tokens[info]};
    color: {tokens[infoFg]};
    border: 1px solid {tokens[info]};
    border-radius: 6px;
    font-size: 13px;
    font-weight: 700;
}}
QPushButton[objectName^="modeInfo"]:hover {{
    border-color: {tokens[infoFg]};
}}
QPushButton[objectName^="modeInfo"]:focus {{
    border-color: {tokens[infoFg]};
}}
QPushButton[objectName^="modeInfo"]:pressed {{
    background-color: {tokens[infoPressed]};
    border-color: {tokens[infoFg]};
}}
QPushButton[objectName^="modeAlt"] {{
    background-color: {tokens[alt]};
    color: {tokens[altFg]};
    border: 1px solid {tokens[alt]};
    border-radius: 6px;
    font-size: 13px;
    font-weight: 700;
}}
QPushButton[objectName^="modeAlt"]:hover {{
    border-color: {tokens[altFg]};
}}
QPushButton[objectName^="modeAlt"]:focus {{
    border-color: {tokens[altFg]};
}}
QPushButton[objectName^="modeAlt"]:pressed {{
    background-color: {tokens[altPressed]};
    border-color: {tokens[altFg]};
}}
QPushButton[objectName^="modeWarn"] {{
    background-color: {tokens[warn]};
    color: {tokens[warnFg]};
    border: 1px solid {tokens[warn]};
    border-radius: 6px;
    font-size: 13px;
    font-weight: 700;
}}
QPushButton[objectName^="modeWarn"]:hover {{
    border-color: {tokens[warnFg]};
}}
QPushButton[objectName^="modeWarn"]:focus {{
    border-color: {tokens[warnFg]};
}}
QPushButton[objectName^="modeWarn"]:pressed {{
    background-color: {tokens[warnPressed]};
    border-color: {tokens[warnFg]};
}}

/* Stop session — destructive (danger) role */
QFrame#stopRow {{
    background-color: transparent;
}}
QPushButton#stopButton {{
    background-color: transparent;
    color: {tokens[danger]};
    border: 1px solid {tokens[danger]};
    border-radius: 6px;
    padding: 7px 22px;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.5px;
}}
QPushButton#stopButton:hover {{
    background-color: {tokens[danger]};
    color: {tokens[dangerFg]};
}}
QPushButton#stopButton:pressed {{
    background-color: {tokens[dangerPressed]};
    color: {tokens[dangerFg]};
    border-color: {tokens[dangerPressed]};
}}
QPushButton#stopButton:disabled {{
    color: {tokens[muted]};
    border-color: {tokens[border]};
}}

/* Log panel header — small label + LED indicator above the log pane */
QFrame#logPanelHeader {{
    background-color: transparent;
}}
QLabel#logLabel {{
    color: {tokens[muted]};
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 1.2px;
}}
QLabel#logLed {{
    color: {tokens[muted]};
    font-size: 10px;
    font-family: ui-monospace, "JetBrains Mono", "Consolas", monospace;
}}

/* Log pane itself */
QPlainTextEdit#logPane {{
    background-color: {tokens[logBg]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    border-radius: 6px;
    margin: 0 24px 16px 24px;
    padding: 10px 14px;
    font-family: "Consolas", ui-monospace, "JetBrains Mono", monospace;
    font-size: 12px;
    selection-background-color: {tokens[selection]};
}}

/* Status bar — label + progress bar.  Per-role label coloring uses
 * the four objectNames the StatusBar widget assigns based on
 * status_role_for_message(). */
QWidget#statusBar {{
    background-color: transparent;
    margin: 4px 24px 0 24px;
}}
QLabel#statusReady {{
    color: {tokens[muted]};
    font-style: italic;
    font-size: 12px;
}}
QLabel#statusBusy {{
    color: {tokens[accent]};
    font-style: italic;
    font-size: 12px;
}}
QLabel#statusWarn {{
    color: {tokens[warn]};
    font-style: italic;
    font-size: 12px;
}}
QLabel#statusError {{
    color: {tokens[danger]};
    font-style: italic;
    font-size: 12px;
}}
QProgressBar#statusProgress {{
    background-color: {tokens[input]};
    border: 1px solid {tokens[border]};
    border-radius: 4px;
    text-align: center;
    color: {tokens[fg]};
    height: 14px;
    font-size: 10px;
}}
QProgressBar#statusProgress::chunk {{
    background-color: {tokens[accent]};
    border-radius: 4px;
}}

/* ---- Tooltip -------------------------------------------------------- */

QToolTip {{
    background-color: {tokens[card]};
    color: {tokens[fg]};
    border: 1px solid {tokens[border]};
    padding: 4px 8px;
}}
"""


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------


def _mix(hex_color: str, factor: float) -> str:
    """Darken (``factor`` < 1) or lighten (``factor`` > 1) a ``#RRGGBB``
    color by scaling each channel toward black or white.

    Used to derive ``:pressed`` shades from a theme's own role colors so
    every theme — built-in or custom — gets correct press feedback with
    no extra tokens to hand-author.  Passes through anything that isn't a
    6-digit hex (e.g. ``transparent``)."""
    s = (hex_color or "").strip()
    if not (s.startswith("#") and len(s) == 7):
        return hex_color
    try:
        r, g, b = int(s[1:3], 16), int(s[3:5], 16), int(s[5:7], 16)
    except ValueError:
        return hex_color
    if factor <= 1.0:
        r, g, b = int(r * factor), int(g * factor), int(b * factor)
    else:
        f = factor - 1.0
        r = int(r + (255 - r) * f)
        g = int(g + (255 - g) * f)
        b = int(b + (255 - b) * f)

    def _c(v: int) -> int:
        return max(0, min(255, v))

    return f"#{_c(r):02x}{_c(g):02x}{_c(b):02x}"


# Press darkens the surface: roles ~18%, neutral surfaces ~10%.
_PRESS_FACTOR = 0.82
_PRESS_FACTOR_NEUTRAL = 0.90


def _derive_interaction_tokens(tokens: Mapping[str, str]) -> dict[str, str]:
    """Pressed-state shades derived from a theme's existing colors.

    Added to the token map only at render time, so themes never need to
    define them (and the up-front coverage check stays unchanged)."""
    out: dict[str, str] = {}
    for role in ("go", "info", "alt", "warn", "danger"):
        out[f"{role}Pressed"] = _mix(tokens[role], _PRESS_FACTOR)
    out["hoverPressed"] = _mix(tokens["hover"], _PRESS_FACTOR_NEUTRAL)
    return out


def render_qss(theme: Theme) -> str:
    """Produce the QSS string for one built-in :class:`Theme`."""
    return render_qss_from_tokens(
        theme.tokens,
        id=theme.id,
        name=theme.name,
        family=theme.family,
        notes=theme.notes,
    )


def render_qss_from_tokens(
    tokens: Mapping[str, str],
    *,
    id: str = "custom",
    name: str = "Custom",
    family: str = "dark",
    notes: str = "",
) -> str:
    """Render QSS from a raw token mapping (built-in or user-made).

    Validates token coverage up front so a missing key gives a clear
    error rather than a ``KeyError`` from inside ``str.format``.  This
    is what the Theme Maker calls for its live preview and what
    ``gui_qt.theme.load_theme`` calls to apply a custom theme.
    """
    missing = [k for k in TOKEN_KEYS if k not in tokens]
    if missing:
        raise ValueError(f"theme {id!r} missing tokens: {missing}")
    # Augment with derived interaction shades (pressed states).  The
    # theme only supplies the base TOKEN_KEYS; the extras live in this
    # render-time copy so the template can reference them.
    render_tokens = {**tokens, **_derive_interaction_tokens(tokens)}
    return _QSS_TEMPLATE.format(
        id=id, name=name, family=family, notes=notes, tokens=render_tokens,
    )
