"""Tests for shared.event.Event and RipperController.emit().

Pinning the actual contract:
- Event is a frozen dataclass record (no pub/sub bus, no subscribers).
- Equality is structural across (type, job_id, data); `data` is held by
  reference, so callers must not mutate it post-construction.
- Event is *not* hashable at runtime even though @dataclass(frozen=True)
  autogenerates __hash__ — `data: Dict` makes hashing raise TypeError.
- RipperController.emit() dispatches to a single optional UI adapter via
  duck-typed `handle_event`. It is silent when ui is None or lacks
  handle_event; it does *not* swallow exceptions raised by the handler.
"""

from dataclasses import FrozenInstanceError

import pytest

from shared.event import Event

from tests.test_behavior_guards import DummyGUI, _engine_cfg
from controller.controller import RipperController
from engine.ripper_engine import RipperEngine


# --------------------------------------------------------------------------
# A. Event dataclass invariants
# --------------------------------------------------------------------------


def test_event_construction_uses_positional_field_order():
    e = Event("log", "job-1", {"message": "hi"})
    assert e.type == "log"
    assert e.job_id == "job-1"
    assert e.data == {"message": "hi"}


def test_event_is_frozen_against_field_assignment():
    e = Event("log", "job-1", {"message": "hi"})
    with pytest.raises(FrozenInstanceError):
        e.type = "progress"  # type: ignore[misc]
    with pytest.raises(FrozenInstanceError):
        e.job_id = "job-2"  # type: ignore[misc]
    with pytest.raises(FrozenInstanceError):
        e.data = {}  # type: ignore[misc]


def test_event_equality_is_structural_across_all_fields():
    a = Event("log", "job-1", {"message": "hi"})
    b = Event("log", "job-1", {"message": "hi"})
    assert a == b
    assert a is not b


@pytest.mark.parametrize(
    "other",
    [
        Event("progress", "job-1", {"message": "hi"}),  # different type
        Event("log", "job-2", {"message": "hi"}),       # different job_id
        Event("log", "job-1", {"message": "bye"}),      # different data
    ],
)
def test_event_inequality_when_any_field_differs(other):
    base = Event("log", "job-1", {"message": "hi"})
    assert base != other


def test_event_data_is_held_by_reference_not_copied():
    """Pin the gotcha: callers must not mutate the dict after construction.
    The frozen flag freezes attribute assignment, not the contents of
    referenced mutable values."""
    payload = {"message": "hi"}
    e = Event("log", "job-1", payload)
    payload["message"] = "mutated"
    assert e.data["message"] == "mutated"


def test_event_is_not_hashable_at_runtime_due_to_dict_data():
    """Frozen dataclasses get an autogenerated __hash__, but Event's
    `data: Dict` makes that hash raise at runtime. Pinning this so a
    refactor to put Event into a set fails loudly here, not in
    production."""
    e = Event("log", "job-1", {"message": "hi"})
    with pytest.raises(TypeError):
        hash(e)


# --------------------------------------------------------------------------
# B. RipperController.emit() semantics
# --------------------------------------------------------------------------


class _RecordingUI(DummyGUI):
    """DummyGUI subclass that captures handle_event calls."""

    def __init__(self):
        super().__init__()
        self.received: list[Event] = []

    def handle_event(self, event: Event) -> None:
        self.received.append(event)


class _RaisingUI(DummyGUI):
    def __init__(self, exc: BaseException):
        super().__init__()
        self._exc = exc

    def handle_event(self, _event: Event) -> None:
        raise self._exc


def _make_controller_with_ui(ui):
    engine = RipperEngine(_engine_cfg())
    return RipperController(engine, ui)


def test_emit_returns_none():
    ui = _RecordingUI()
    controller = _make_controller_with_ui(ui)
    result = controller.emit(Event("log", "job-1", {"message": "hi"}))
    assert result is None


def test_emit_dispatches_event_to_handle_event_exactly_once():
    ui = _RecordingUI()
    controller = _make_controller_with_ui(ui)
    event = Event("log", "job-1", {"message": "hi"})

    controller.emit(event)

    assert len(ui.received) == 1
    assert ui.received[0] is event  # same object, not copied


def test_emit_is_silent_when_ui_is_none():
    """Pin the no-UI fast path. Tests must not require a UI to drive code
    that emits — emit() short-circuits cleanly."""
    controller = _make_controller_with_ui(_RecordingUI())
    controller.ui = None  # simulate headless / no-UI mode

    controller.emit(Event("log", "job-1", {"message": "hi"}))  # must not raise


def test_emit_is_silent_when_ui_lacks_handle_event():
    """Pin the duck-typed contract. A UI without handle_event is treated
    as opt-out, not an error — emit() must not AttributeError."""
    ui = DummyGUI()  # has set_status / append_log / etc., but no handle_event
    assert not hasattr(ui, "handle_event")
    controller = _make_controller_with_ui(ui)

    controller.emit(Event("log", "job-1", {"message": "hi"}))  # must not raise


def test_emit_does_not_swallow_handler_exceptions():
    """Pin the exception contract. The worker loop in controller.worker()
    catches exceptions from the engine streaming loop, but emit() itself
    is not a safety net — handler bugs propagate to the caller."""
    boom = RuntimeError("ui handler exploded")
    controller = _make_controller_with_ui(_RaisingUI(boom))

    with pytest.raises(RuntimeError, match="ui handler exploded"):
        controller.emit(Event("log", "job-1", {"message": "hi"}))
