from typing import Protocol
from shared.event import Event

class UIAdapter(Protocol):
    def handle_event(self, event: Event) -> None: ...
    def on_progress(self, job_id: str, value: float) -> None: ...
    def on_log(self, job_id: str, message: str) -> None: ...
    def on_error(self, job_id: str, error: Exception) -> None: ...
    def on_complete(self, job_id: str) -> None: ...
